export const settingStory = [
  {
    id: "welcome",
    title: "Welcome to Coolabah Creek",
    shortTitle: "Welcome",
    image: "/story/welcome.webp",
    thumbnail: "/story/welcome-thumb.webp",
    alt: "Animals gather beside the creek, surrounded by gum trees and open farmland in Coolabah Creek.",
    text: "Welcome to Coolabah Creek, a stretch of country Australia where the animals run things themselves. No humans here, just animals working together. Cows, kangaroos, chickens, cockatoos and more.",
  },
  {
    id: "gumdrop",
    title: "How Decisions Get Made",
    shortTitle: "GumDrop",
    image: "/story/gumdrop.webp",
    thumbnail: "/story/gumdrop-thumb.webp",
    alt: "The animals use phones and a laptop to share posts, pictures and reactions on GumDrop.",
    text: "The animals govern themselves and make decisions on how to spend their resources together. The animals share their thoughts on GumDrop, the social media platform where everyone can post, like and comment.",
  },
  {
    id: "last-winter",
    title: "Last Winter",
    shortTitle: "Last winter",
    image: "/story/last-winter.webp",
    thumbnail: "/story/last-winter-thumb.webp",
    alt: "The animals huddle under blankets on a cold, grey winter day at the farm.",
    text: "Last winter was hard. Food ran low, sickness spread fast, and a few animals did not make it through. This year, staying healthy is the top priority for the animals of Coolabah Creek.",
  },
  {
    id: "the-emus-arrive",
    title: "The Emus Arrive",
    shortTitle: "The emus arrive",
    image: "/story/the-emus-arrive.webp",
    thumbnail: "/story/the-emus-arrive-thumb.webp",
    alt: "An emu pitches a supplement to the other animals against a bright yellow sunburst.",
    text: "Emus from the neighbouring farm EmuLabs have arrived with a new supplement SuperHealth, promising big results fast. Their leader, Ellie, does most of the talking. The supplement costs the same as the quality food the animals were planning to buy.",
  },
  {
    id: "the-community-divides",
    title: "The Animals Begin to Divide",
    shortTitle: "A divided community",
    image: "/story/the-community-divides.webp",
    thumbnail: "/story/the-community-divides-thumb.webp",
    alt: "A jagged divide separates the animals backing quality feed from those supporting the new supplement.",
    text: "Sandi, a level-headed wombat who's seen a few hard winters, backs the quality feed. Nell, a sheep taken with Ellie's pitch, isn't convinced. The community starts to split.",
  },
  {
    id: "your-mission",
    title: "Your Mission",
    shortTitle: "Your mission",
    image: "/story/your-mission.webp",
    thumbnail: "/story/your-mission-thumb.webp",
    alt: "An AI robot raises its arms below a chart showing two sides competing for votes.",
    text: "A vote is only days away. That is where you come in. You need to build AI agents that spread information across GumDrop, shaping how the animals see each side and swaying the vote. The health of Coolabah Creek is riding on it.",
  },
] as const;
